generatorName: typescript-angular
outputDir: ../justice-system-web/src/app/generated
inputSpec: '/src/main/resources/justice-system-v1.yaml'
generateApis: false
templateDir: justice-system-openapi/src/main/resources/templates
typeMappings:
  DateTime: "Date"
  Date: "Date"
  date: "Date"
additionalProperties:
  mat-form-field-appearance: outline
  fileNaming: kebab-case
files:
  modelGeneric.mustache:
    templateType: Model
    destinationFilename: .ts
  modelFormHtml.mustache:
    templateType: Model
    destinationFilename: .form.component.html
    folder: form-components
  modelFormComponent.mustache:
    templateType: Model
    destinationFilename: .form.component.ts
    folder: form-components
  formReviewComponent.mustache:
    templateType: Model
    destinationFilename: .review.component.ts
    folder: review-components
  formReviewHtml.mustache:
    templateType: Model
    destinationFilename: .review.component.html
    folder: review-components
