name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run tests
      run: mvn -B test
    
  web-build:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: justice-system-web/package-lock.json
    
    - name: Generate Angular components
      run: mvn clean generate-sources -pl justice-system-openapi -am -P custom-frontend
    
    - name: Install dependencies
      run: |
        cd justice-system-web
        npm ci
    
    - name: Build Angular app
      run: |
        cd justice-system-web
        npm run build -- --configuration production
    
    - name: Run Angular tests
      run: |
        cd justice-system-web
        npm run test -- --watch=false --browsers=ChromeHeadless
  
  ai-build:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Generate Python models
      run: mvn clean generate-sources -pl justice-system-openapi -am -P python-models
    
    - name: Install uv
      run: pip install uv
    
    - name: Install dependencies
      run: |
        cd justice-system-ai
        uv pip install -e ".[dev]"
    
    - name: Run Python tests
      run: |
        cd justice-system-ai
        pytest
