name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '30 1 * * *'  # Run at 1:30 AM UTC every day

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        
        # Issue settings
        stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
        close-issue-message: 'This issue has been automatically closed due to inactivity. Please feel free to reopen it if you believe it still needs attention.'
        days-before-issue-stale: 60
        days-before-issue-close: 14
        exempt-issue-labels: 'pinned,security,bug,enhancement,documentation,good first issue'
        
        # Pull request settings
        stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
        close-pr-message: 'This pull request has been automatically closed due to inactivity. Please feel free to reopen it if you believe it still needs attention.'
        days-before-pr-stale: 30
        days-before-pr-close: 14
        exempt-pr-labels: 'pinned,security,work-in-progress,dependencies'
        
        # General settings
        exempt-all-milestones: true
        exempt-all-assignees: false
        operations-per-run: 100
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        remove-stale-when-updated: true
        debug-only: false
